In [2]:
import pandas as pd
import os

In [3]:
os.getcwd()

'/home/jupyter/deepthim'

In [4]:
df=pd.read_parquet("/home/jupyter/deepthim/crypto_market_data.parquet")

In [5]:
df.shape

(325741, 17)

In [6]:
df

,date,coin_id,ticker,open,high,low,close,volume,market_cap,protocol_tvl,dex_volume,lc_galaxy_score,lc_alt_rank,lc_social_dominance,lc_sentiment,chain_tvl,canonical_id
0,2022-01-01,0x,None,NaN,NaN,NaN,0.806868,6.143749e+07,6.862059e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0x
1,2022-01-02,0x,None,NaN,NaN,NaN,0.866089,6.455163e+07,7.294317e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0x
2,2022-01-03,0x,None,NaN,NaN,NaN,0.891073,6.766605e+07,7.569679e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0x
3,2022-01-04,0x,None,0.795818,0.976327,0.778135,0.944689,1.276283e+08,8.012985e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0x
4,2022-01-05,0x,None,NaN,NaN,NaN,0.897177,6.264864e+07,7.635232e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0x
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325736,2025-01-28,zksync,None,0.155714,0.160138,0.133995,0.143751,8.851999e+07,5.276905e+08,NaN,NaN,NaN,NaN,NaN,NaN,278271470.0,zksync
325737,2025-01-29,zksync,None,NaN,NaN,NaN,0.132423,4.602350e+07,4.864731e+08,NaN,NaN,NaN,NaN,NaN,NaN,270510025.0,zksync
325738,2025-01-30,zksync,None,NaN,NaN,NaN,0.138207,5.569715e+07,5.089980e+08,NaN,NaN,NaN,NaN,NaN,NaN,280228233.0,zksync
325739,2025-01-31,zksync,None,NaN,NaN,NaN,0.145761,4.393869e+07,5.363103e+08,NaN,NaN,NaN,NaN,NaN,NaN,287237152.0,zksync
325740,2025-02-01,zksync,None,0.144056,0.159277,0.130960,0.152019,7.889405e+07,5.587506e+08,NaN,NaN,NaN,NaN,NaN,NaN,291663361.0,zksync

In [7]:
Factor	Crypto Analogue	What You Need	DIY Strategy
MKT	CMKT	Prices + Market Caps	Cap-weighted return minus risk-free
SMB	CSMB	Market Caps	Return of small-cap coins – large-cap
HML	CHML	Fundamental-like proxies (e.g. price/supply)	Use pseudo "book/market" (e.g. low price/high market cap)
MOM	CMOM	Price history	High 30-day momentum – Low 30-day momentum
VOL	CVOL	Price stddev	Low-volatility vs high-volatility
LIQ	CLIQ	Volume, spread	High-volume coins vs low-volume

SyntaxError: invalid character '–' (U+2013) (3563092984.py, line 3)

In [8]:
#cmkt
#SMB
#Valuefsctor
#CMA
da=pd.DataFrame()
da=df[['market_cap','canonical_id']].copy()
da

          market_cap canonical_id
0       6.862059e+08           0x
1       7.294317e+08           0x
2       7.569679e+08           0x
3       8.012985e+08           0x
4       7.635232e+08           0x
...              ...          ...
325736  5.276905e+08       zksync
325737  4.864731e+08       zksync
325738  5.089980e+08       zksync
325739  5.363103e+08       zksync
325740  5.587506e+08       zksync

[325741 rows x 2 columns]

In [9]:
#calculating stablecoin APY forCompund DataSource: \
rfv=(1+(0.0167/100))**(1/365)-1
rfv

4.5749615140699973e-07

In [10]:
def excessreturns(mktreturns):
    a=mktreturns-rfv
    return a

In [11]:
#Cmkt
def cmkt(df):
    da=pd.DataFrame()
    da=df[['market_cap','canonical_id']].copy()
    da['market_returns']=da['market_cap'].pct_change()
    #da['riskfreeval']=(1+(apy/100))**(1/365)-1
    da['cmkt']=da['market_returns'].apply(excessreturns)
    return da


dataset=cmkt(df)
df=pd.concat([df,dataset[['market_returns','cmkt']]],axis=1)
df

,date,coin_id,ticker,open,high,low,close,volume,market_cap,protocol_tvl,dex_volume,lc_galaxy_score,lc_alt_rank,lc_social_dominance,lc_sentiment,chain_tvl,canonical_id,market_returns,cmkt
0,2022-01-01,0x,None,NaN,NaN,NaN,0.806868,6.143749e+07,6.862059e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0x,NaN,NaN
1,2022-01-02,0x,None,NaN,NaN,NaN,0.866089,6.455163e+07,7.294317e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0x,0.062992,0.062992
2,2022-01-03,0x,None,NaN,NaN,NaN,0.891073,6.766605e+07,7.569679e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0x,0.037750,0.037750
3,2022-01-04,0x,None,0.795818,0.976327,0.778135,0.944689,1.276283e+08,8.012985e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0x,0.058563,0.058563
4,2022-01-05,0x,None,NaN,NaN,NaN,0.897177,6.264864e+07,7.635232e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0x,-0.047143,-0.047143
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325736,2025-01-28,zksync,None,0.155714,0.160138,0.133995,0.143751,8.851999e+07,5.276905e+08,NaN,NaN,NaN,NaN,NaN,NaN,278271470.0,zksync,-0.035861,-0.035862
325737,2025-01-29,zksync,None,NaN,NaN,NaN,0.132423,4.602350e+07,4.864731e+08,NaN,NaN,NaN,NaN,NaN,NaN,270510025.0,zksync,-0.078109,-0.078109
325738,2025-01-30,zksync,None,NaN,NaN,NaN,0.138207,5.569715e+07,5.089980e+08,NaN,NaN,NaN,NaN,NaN,NaN,280228233.0,zksync,0.046303,0.046302
325739,2025-01-31,zksync,None,NaN,NaN,NaN,0.145761,4.393869e+07,5.363103e+08,NaN,NaN,NaN,NaN,NaN,NaN,287237152.0,zksync,0.053659,0.053658
325740,2025-02-01,zksync,None,0.144056,0.159277,0.130960,0.152019,7.889405e+07,5.587506e+08,NaN,NaN,NaN,NaN,NaN,NaN,291663361.0,zksync,0.041842,0.041842

In [12]:
#calc market return

#risk free rate
#calc excess returns
#Annualized Percentage Yields

In [13]:
rfv=(1+(0.0167/100))**(1/365)-1

In [14]:
rfv
#marketreturn-riskfreemarketeturn

4.5749615140699973e-07

In [15]:
da

          market_cap canonical_id
0       6.862059e+08           0x
1       7.294317e+08           0x
2       7.569679e+08           0x
3       8.012985e+08           0x
4       7.635232e+08           0x
...              ...          ...
325736  5.276905e+08       zksync
325737  4.864731e+08       zksync
325738  5.089980e+08       zksync
325739  5.363103e+08       zksync
325740  5.587506e+08       zksync

[325741 rows x 2 columns]

In [16]:
#value = (TVL / MarketCap)
#hml_signal = 1 / value
def hml(df):
    de=pd.DataFrame()
    de=df[['market_cap','canonical_id','protocol_tvl']].copy()
    de['market_cap']
    de['value']=de['protocol_tvl']/de['market_cap']
    de['hml']=1/de['value']
    return de

de=hml(df)
df = pd.concat([df,de[['value','hml']]],axis=1)

In [17]:

#de['tvl']=df['protocol_tvl'].copy().dropna()

In [18]:
#calculate smb
def smb(df):
    dea=df.copy()
    dea['returns']=df['close'].pct_change()
    dea=df.sort_values('market_cap',ascending=True)
    dea['returns']=df['close'].pct_change()
    numtokens=len(dea)
    val=int(numtokens*0.3)
    deas=dea.head(val)
    deal=dea.tail(val)
    dea['smb']=deas['returns'].mean()-deal['returns'].mean()
    return dea
dea=smb(df)
df=pd.concat([df,dea['smb']],axis=1)

In [19]:
dea['returns']=dea['close'].pct_change()

In [20]:
def rmw(df):
    deb=df.copy()
    deb['estimated_revenue'] = deb['dex_volume'] * 0.003
    deb['revenue_to_tvl'] = deb['estimated_revenue'] / deb['protocol_tvl']
    return deb
deb=rmw(df)
df=pd.concat([df,deb[['estimated_revenue','revenue_to_tvl']]],axis=1)

In [21]:
# DefiLlama: daily supply via /api/v1/supply/{token}
#cma_signal = pct_change(supply)  # or pct_change(TVL)

In [22]:
mom_1m = df['close'].pct_change(30)
mom_1w = df['close'].pct_change(7)
wml = mom_1m - mom_1w

In [23]:
df

,date,coin_id,ticker,open,high,low,close,volume,market_cap,protocol_tvl,...,lc_sentiment,chain_tvl,canonical_id,market_returns,cmkt,value,hml,smb,estimated_revenue,revenue_to_tvl
0,2022-01-01,0x,None,NaN,NaN,NaN,0.806868,6.143749e+07,6.862059e+08,NaN,...,NaN,NaN,0x,NaN,NaN,NaN,NaN,70630.153961,NaN,NaN
1,2022-01-02,0x,None,NaN,NaN,NaN,0.866089,6.455163e+07,7.294317e+08,NaN,...,NaN,NaN,0x,0.062992,0.062992,NaN,NaN,70630.153961,NaN,NaN
2,2022-01-03,0x,None,NaN,NaN,NaN,0.891073,6.766605e+07,7.569679e+08,NaN,...,NaN,NaN,0x,0.037750,0.037750,NaN,NaN,70630.153961,NaN,NaN
3,2022-01-04,0x,None,0.795818,0.976327,0.778135,0.944689,1.276283e+08,8.012985e+08,NaN,...,NaN,NaN,0x,0.058563,0.058563,NaN,NaN,70630.153961,NaN,NaN
4,2022-01-05,0x,None,NaN,NaN,NaN,0.897177,6.264864e+07,7.635232e+08,NaN,...,NaN,NaN,0x,-0.047143,-0.047143,NaN,NaN,70630.153961,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325736,2025-01-28,zksync,None,0.155714,0.160138,0.133995,0.143751,8.851999e+07,5.276905e+08,NaN,...,NaN,278271470.0,zksync,-0.035861,-0.035862,NaN,NaN,70630.153961,NaN,NaN
325737,2025-01-29,zksync,None,NaN,NaN,NaN,0.132423,4.602350e+07,4.864731e+08,NaN,...,NaN,270510025.0,zksync,-0.078109,-0.078109,NaN,NaN,70630.153961,NaN,NaN
325738,2025-01-30,zksync,None,NaN,NaN,NaN,0.138207,5.569715e+07,5.089980e+08,NaN,...,NaN,280228233.0,zksync,0.046303,0.046302,NaN,NaN,70630.153961,NaN,NaN
325739,2025-01-31,zksync,None,NaN,NaN,NaN,0.145761,4.393869e+07,5.363103e+08,NaN,...,NaN,287237152.0,zksync,0.053659,0.053658,NaN,NaN,70630.153961,NaN,NaN
325740,2025-02-01,zksync,None,0.144056,0.159277,0.130960,0.152019,7.889405e+07,5.587506e+08,NaN,...,NaN,291663361.0,zksync,0.041842,0.041842,NaN,NaN,70630.153961,NaN,NaN

In [ ]:
#these are cross-sectional, comparing the asset to other assets on the same day.
#these are cross-sectional, comparing the asset to other assets on the same day.

In [41]:
#btc_dominance
total_mcap = df.groupby('date')['market_cap'].sum()
btc_mcap = df[df['ticker'] == 'bitcoin'].set_index('date')['market_cap']
df['btc_dominance'] = (btc_mcap / total_mcap) * 100

In [ ]:
def calculate_altcoin_dominance(df):
    daily_top10 = df.groupby('date').apply(
        lambda x: x.nlargest(10, 'market_cap')['market_cap'].sum())
    total_mcap = df.groupby('date')['market_cap'].sum()
    altcoin_dominance = ((total_mcap - daily_top10) / total_mcap) * 100
    return df['date'].map(altcoin_dominance)

In [25]:
total_market_cap

date
2022-01-01    1.329439e+12
2022-01-02    1.365386e+12
2022-01-03    1.378050e+12
2022-01-04    1.359115e+12
2022-01-05    1.363584e+12
                  ...
2025-06-27    1.214919e+12
2025-06-28    1.224356e+12
2025-06-29    1.239259e+12
2025-06-30    1.261124e+12
2025-07-01    1.255211e+12
Name: market_cap, Length: 1278, dtype: float64

In [39]:
df.dropna()
df

,date,coin_id,ticker,open,high,low,close,volume,market_cap,protocol_tvl,...,chain_tvl,canonical_id,market_returns,cmkt,value,hml,smb,estimated_revenue,revenue_to_tvl,btc_dominance
0,2022-01-01,0x,None,NaN,NaN,NaN,0.806868,6.143749e+07,6.862059e+08,NaN,...,NaN,0x,NaN,NaN,NaN,NaN,70630.153961,NaN,NaN,NaN
1,2022-01-02,0x,None,NaN,NaN,NaN,0.866089,6.455163e+07,7.294317e+08,NaN,...,NaN,0x,0.062992,0.062992,NaN,NaN,70630.153961,NaN,NaN,NaN
2,2022-01-03,0x,None,NaN,NaN,NaN,0.891073,6.766605e+07,7.569679e+08,NaN,...,NaN,0x,0.037750,0.037750,NaN,NaN,70630.153961,NaN,NaN,NaN
3,2022-01-04,0x,None,0.795818,0.976327,0.778135,0.944689,1.276283e+08,8.012985e+08,NaN,...,NaN,0x,0.058563,0.058563,NaN,NaN,70630.153961,NaN,NaN,NaN
4,2022-01-05,0x,None,NaN,NaN,NaN,0.897177,6.264864e+07,7.635232e+08,NaN,...,NaN,0x,-0.047143,-0.047143,NaN,NaN,70630.153961,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325736,2025-01-28,zksync,None,0.155714,0.160138,0.133995,0.143751,8.851999e+07,5.276905e+08,NaN,...,278271470.0,zksync,-0.035861,-0.035862,NaN,NaN,70630.153961,NaN,NaN,NaN
325737,2025-01-29,zksync,None,NaN,NaN,NaN,0.132423,4.602350e+07,4.864731e+08,NaN,...,270510025.0,zksync,-0.078109,-0.078109,NaN,NaN,70630.153961,NaN,NaN,NaN
325738,2025-01-30,zksync,None,NaN,NaN,NaN,0.138207,5.569715e+07,5.089980e+08,NaN,...,280228233.0,zksync,0.046303,0.046302,NaN,NaN,70630.153961,NaN,NaN,NaN
325739,2025-01-31,zksync,None,NaN,NaN,NaN,0.145761,4.393869e+07,5.363103e+08,NaN,...,287237152.0,zksync,0.053659,0.053658,NaN,NaN,70630.153961,NaN,NaN,NaN
325740,2025-02-01,zksync,None,0.144056,0.159277,0.130960,0.152019,7.889405e+07,5.587506e+08,NaN,...,291663361.0,zksync,0.041842,0.041842,NaN,NaN,70630.153961,NaN,NaN,NaN

In [25]:
df.isnull().sum()

date                        0
coin_id                     0
ticker                 238680
open                   244739
high                   244739
low                    244739
close                       0
volume                      0
market_cap                  0
protocol_tvl           278280
dex_volume             319030
lc_galaxy_score        247040
lc_alt_rank            247263
lc_social_dominance    242345
lc_sentiment           244710
chain_tvl              244146
canonical_id                0
market_returns          20863
cmkt                    20863
value                  278280
hml                    278280
smb                         0
estimated_revenue      319030
revenue_to_tvl         319070
dtype: int64

In [26]:
df.dtypes

date                   datetime64[ns]
coin_id                        object
ticker                         object
open                          float64
high                          float64
low                           float64
close                         float64
volume                        float64
market_cap                    float64
protocol_tvl                  float64
dex_volume                    float64
lc_galaxy_score               float64
lc_alt_rank                   float64
lc_social_dominance           float64
lc_sentiment                  float64
chain_tvl                     float64
canonical_id                   object
market_returns                float64
cmkt                          float64
value                         float64
hml                           float64
smb                           float64
estimated_revenue             float64
revenue_to_tvl                float64
dtype: object

In [27]:
df.dropna()

,date,coin_id,ticker,open,high,low,close,volume,market_cap,protocol_tvl,...,lc_sentiment,chain_tvl,canonical_id,market_returns,cmkt,value,hml,smb,estimated_revenue,revenue_to_tvl
83133,2022-01-04,crypto-com-chain,CRO,0.553823,0.591482,0.550321,0.568043,1.928124e+08,1.439227e+10,5.102612e+07,...,79.0,1.954889e+09,crypto-com-chain,-0.033209,-0.033209,0.003545,282.056909,70630.153961,7717.338,0.000151
83137,2022-01-08,crypto-com-chain,CRO,0.568791,0.576110,0.462686,0.464167,2.536358e+08,1.175941e+10,4.772945e+07,...,83.0,1.775166e+09,crypto-com-chain,-0.078949,-0.078950,0.004059,246.376389,70630.153961,10109.760,0.000212
83141,2022-01-12,crypto-com-chain,CRO,0.466068,0.483872,0.426444,0.459536,1.496617e+08,1.164026e+10,4.772188e+07,...,79.0,1.857950e+09,crypto-com-chain,0.035351,0.035350,0.004100,243.918655,70630.153961,4652.808,0.000097
83145,2022-01-16,crypto-com-chain,CRO,0.459615,0.495329,0.447699,0.468410,1.233178e+08,1.182101e+10,4.846709e+07,...,85.0,1.891961e+09,crypto-com-chain,0.025812,0.025811,0.004100,243.897702,70630.153961,4299.966,0.000089
83149,2022-01-20,crypto-com-chain,CRO,0.468143,0.472792,0.431717,0.433660,1.277283e+08,1.096044e+10,4.610678e+07,...,100.0,1.884323e+09,crypto-com-chain,-0.027563,-0.027563,0.004207,237.718542,70630.153961,5980.632,0.000130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84389,2025-06-13,crypto-com-chain,CRO,0.097936,0.101916,0.095624,0.096754,2.162004e+07,2.893415e+09,1.131225e+06,...,83.0,5.764926e+08,crypto-com-chain,-0.021411,-0.021411,0.000391,2557.770723,70630.153961,1062.240,0.000939
84393,2025-06-17,crypto-com-chain,CRO,0.096555,0.096555,0.088465,0.090792,1.895833e+07,2.715564e+09,1.116712e+06,...,88.0,5.705799e+08,crypto-com-chain,-0.000559,-0.000560,0.000411,2431.750611,70630.153961,153.621,0.000138
84397,2025-06-21,crypto-com-chain,CRO,0.090468,0.093220,0.085513,0.087967,2.114826e+07,2.736647e+09,1.084091e+06,...,88.0,5.478864e+08,crypto-com-chain,-0.030986,-0.030986,0.000396,2524.370041,70630.153961,177.066,0.000163
84401,2025-06-25,crypto-com-chain,CRO,0.088055,0.088912,0.077526,0.084239,1.884893e+07,2.620289e+09,1.088485e+06,...,88.0,5.443551e+08,crypto-com-chain,-0.007132,-0.007132,0.000415,2407.281143,70630.153961,153.462,0.000141
84405,2025-06-29,crypto-com-chain,CRO,0.084277,0.084494,0.079915,0.081117,8.680343e+06,2.522863e+09,1.077014e+06,...,88.0,5.369516e+08,crypto-com-chain,0.001589,0.001589,0.000427,2342.461829,70630.153961,132.834,0.000123

In [30]:
from sklearn.preprocessing import OneHotEncoder

In [33]:
ohe=OneHotEncoder(drop='first',dtype='int',sparse_output=False)
df['canonical_id']=ohe.fit_transform(df[['canonical_id']])
df['ticker']=ohe.fit_transform(df[['ticker']])
df['coin_id']=ohe.fit_transform(df[['coin_id']])
#dataset=dataset.drop('timestamp',axis=1)
df.dtypes

date                   datetime64[ns]
coin_id                         int64
ticker                          int64
open                          float64
high                          float64
low                           float64
close                         float64
volume                        float64
market_cap                    float64
protocol_tvl                  float64
dex_volume                    float64
lc_galaxy_score               float64
lc_alt_rank                   float64
lc_social_dominance           float64
lc_sentiment                  float64
chain_tvl                     float64
canonical_id                    int64
market_returns                float64
cmkt                          float64
value                         float64
hml                           float64
smb                           float64
estimated_revenue             float64
revenue_to_tvl                float64
dtype: object

In [34]:
df

,date,coin_id,ticker,open,high,low,close,volume,market_cap,protocol_tvl,...,lc_sentiment,chain_tvl,canonical_id,market_returns,cmkt,value,hml,smb,estimated_revenue,revenue_to_tvl
0,2022-01-01,0,0,NaN,NaN,NaN,0.806868,6.143749e+07,6.862059e+08,NaN,...,NaN,NaN,0,NaN,NaN,NaN,NaN,70630.153961,NaN,NaN
1,2022-01-02,0,0,NaN,NaN,NaN,0.866089,6.455163e+07,7.294317e+08,NaN,...,NaN,NaN,0,0.062992,0.062992,NaN,NaN,70630.153961,NaN,NaN
2,2022-01-03,0,0,NaN,NaN,NaN,0.891073,6.766605e+07,7.569679e+08,NaN,...,NaN,NaN,0,0.037750,0.037750,NaN,NaN,70630.153961,NaN,NaN
3,2022-01-04,0,0,0.795818,0.976327,0.778135,0.944689,1.276283e+08,8.012985e+08,NaN,...,NaN,NaN,0,0.058563,0.058563,NaN,NaN,70630.153961,NaN,NaN
4,2022-01-05,0,0,NaN,NaN,NaN,0.897177,6.264864e+07,7.635232e+08,NaN,...,NaN,NaN,0,-0.047143,-0.047143,NaN,NaN,70630.153961,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325736,2025-01-28,0,0,0.155714,0.160138,0.133995,0.143751,8.851999e+07,5.276905e+08,NaN,...,NaN,278271470.0,0,-0.035861,-0.035862,NaN,NaN,70630.153961,NaN,NaN
325737,2025-01-29,0,0,NaN,NaN,NaN,0.132423,4.602350e+07,4.864731e+08,NaN,...,NaN,270510025.0,0,-0.078109,-0.078109,NaN,NaN,70630.153961,NaN,NaN
325738,2025-01-30,0,0,NaN,NaN,NaN,0.138207,5.569715e+07,5.089980e+08,NaN,...,NaN,280228233.0,0,0.046303,0.046302,NaN,NaN,70630.153961,NaN,NaN
325739,2025-01-31,0,0,NaN,NaN,NaN,0.145761,4.393869e+07,5.363103e+08,NaN,...,NaN,287237152.0,0,0.053659,0.053658,NaN,NaN,70630.153961,NaN,NaN
325740,2025-02-01,0,0,0.144056,0.159277,0.130960,0.152019,7.889405e+07,5.587506e+08,NaN,...,NaN,291663361.0,0,0.041842,0.041842,NaN,NaN,70630.153961,NaN,NaN

In [36]:
import datetime as dt
df['year']=df['date'].dt.year
df['month']=df['date'].dt.month
df['day']=df['date'].dt.day

In [47]:
df.drop('date',axis=1,inplace=True)

In [74]:
df=df.dropna()

In [49]:
from sklearn.model_selection import train_test_split

In [75]:
X=df.drop(columns='close',axis=1)
y=df['close']

In [76]:
X_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [77]:
from xgboost import XGBRegressor
#from sklearn.model_selection import traintestsplit
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [61]:
pip install xgboost

Requirement already satisfied: xgboost in /opt/conda/lib/python3.10/site-packages (3.0.2)
Requirement already satisfied: numpy in /opt/conda/lib/python3.10/site-packages (from xgboost) (2.1.3)
Requirement already satisfied: nvidia-nccl-cu12 in /opt/conda/lib/python3.10/site-packages (from xgboost) (2.27.6)
Requirement already satisfied: scipy in /opt/conda/lib/python3.10/site-packages (from xgboost) (1.15.3)
Note: you may need to restart the kernel to use updated packages.

In [78]:
xgb=XGBRegressor()
xgb.fit(X_train,y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)